module.exports = {
    pageTitleSel : 'div#titleSection span',
    pageRatingSel : 'span#acrCustomerReviewText.a-size-base',
    pagePriceSel : 'div#price span',
    addToCartSel : '#add-to-cart-button',
    cartSel : '#nav-cart-count',
    addToWishListButton : 'input#add-to-wishlist-button-submit',
    buyNowButton : 'input#buy-now-button',
    deliveryAddressSelector : 'div#addres-select h1',
    deliverToThisAddressButton : 'div.address-book div.ship-to-this-address a',
    paymentMethodSelector : 'div.a-container h1',
    addCardRadioButton : 'input[name="ppw-instrumentRowSelection"]',
    addCreditOrDebitCardLink : 'div.pmts-instrument-box a',
    viewWishListButton : 'span.w-button-text',
    cardNumberPopUp : 'div.apx-add-credit-card-number input',
    nameOnCardPopUp : 'div.pmts-customer-card-name-input-box input',
    expiryMonthDropDownButton :'span.pmts-expiry-month span.a-button-inner span',
    expiryMonth : 'div#a-popover-2 ul li:nth-child(9) a',
    expiryYearDropDownButton : 'span.pmts-expiry-year span.a-button-inner span',
    expiryYear : 'div#a-popover-3 ul li:nth-child(1) a',
    addYouCardButton : 'div.apx-add-card-buttons-in-popover input',
    savedCardRadioButton : 'div.pmts-credit-card-row input',
    CVVCardText : 'div.pmts-credit-card-verification input' 
}